# Generated by Django 5.2.10 on 2026-01-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittransaction',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='posted_by',
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(help_text='Comma separated skills'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
